server:
  port: 8082
spring:
  application:
    name: Login
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: Demo
    password: root
    url: jdbc:mysql://localhost:3306/spring_boot
    username: root
  jpa:
    hibernate:
      ddl-auto: update
